# =============================================================================
# Secrets Manager entries.
#
# Two kinds:
#   generated - Terraform invents the value (passwords, JWT signing keys). The
#               plaintext is an output consumed only by modules/database, and
#               is never surfaced at the root (see ../../outputs.tf).
#   operator  - Terraform creates the *container* with a placeholder. A human
#               puts the real value in, because these come from third parties
#               (Google OAuth, Alibaba DashScope, OpenAI) and must never sit in
#               state or in a tfvars file.
#
# Rotation is left to the operator: rotating the JWT secrets invalidates every
# live session, so it is a deliberate act, not a schedule.
# =============================================================================

locals {
  generated_secrets = {
    "jwt-access-secret"          = { length = 64, special = false }
    "jwt-refresh-secret"         = { length = 64, special = false }
    "internal-service-token"     = { length = 48, special = false }
    "rds-password"               = { length = 32, special = false }
    "docdb-password"             = { length = 32, special = false }
    "redis-auth-token"           = { length = 48, special = false }
    "opensearch-master-password" = { length = 24, special = true }
  }

  operator_secrets = [
    "google-client-id",
    "google-client-secret",
    "dashscope-api-key",
    "openai-api-key",
  ]
}

# DocumentDB and ElastiCache reject several punctuation characters in
# passwords, and an unlucky generated value fails the apply hours in. Only the
# OpenSearch master password takes specials, from a hand-checked set.
resource "random_password" "generated" {
  for_each = local.generated_secrets

  length           = each.value.length
  special          = each.value.special
  override_special = "!#$%^&*()-_=+"
  min_upper        = 2
  min_lower        = 2
  min_numeric      = 2
}

resource "aws_secretsmanager_secret" "generated" {
  for_each = local.generated_secrets

  name                    = "${var.secret_prefix}/${each.key}"
  description             = "${var.name_prefix} ${each.key} (generated by Terraform)"
  kms_key_id              = var.kms_key_arn
  recovery_window_in_days = var.recovery_window_days

  tags = merge(var.tags, { Name = "${var.secret_prefix}/${each.key}", Managed = "terraform" })
}

resource "aws_secretsmanager_secret_version" "generated" {
  for_each = local.generated_secrets

  secret_id     = aws_secretsmanager_secret.generated[each.key].id
  secret_string = random_password.generated[each.key].result
}

resource "aws_secretsmanager_secret" "operator" {
  for_each = toset(local.operator_secrets)

  name                    = "${var.secret_prefix}/${each.value}"
  description             = "${var.name_prefix} ${each.value}. ${var.operator_managed_notes}"
  kms_key_id              = var.kms_key_arn
  recovery_window_in_days = var.recovery_window_days

  tags = merge(var.tags, { Name = "${var.secret_prefix}/${each.value}", Managed = "operator" })
}

# A placeholder version so ECS can resolve the ARN on the very first deploy.
# `ignore_changes` means a later `put-secret-value` is never reverted by a plan.
resource "aws_secretsmanager_secret_version" "operator_placeholder" {
  for_each = toset(local.operator_secrets)

  secret_id     = aws_secretsmanager_secret.operator[each.value].id
  secret_string = "REPLACE_ME"

  lifecycle {
    ignore_changes = [secret_string]
  }
}
